### ISSUE TITLE
GetLinkCode([User ID]) Returning with nil

### ISSUE THREAD

**Issue by TH4RDY** [jdwoj5/hub-linkbot#3]
When trying to get a link code, It keeps on returning with nil.

**Comment by jdwoj5** [comment]
Any errors? Did you add a User ID? Did you fill in your port and IP correctly?

**Comment by TH4RDY** [comment]
Yes, I added the id, I also added the port. What do i need to do with ip ?

**Comment by jdwoj5** [comment]
Nothing, just make sure you are using the correct IP. Does it error out at all?

**Comment by jdwoj5** [comment]
Also make sure the bot is running 24/7 wherever you are hosting it.

**Comment by TH4RDY** [comment]
No, I'm using a vps so how would i get an ip and there is no errors, It just states as i got it to print in the output 'nil'.

**Comment by TH4RDY** [comment]
Wait do i need both Ip/Port ?

**Comment by TH4RDY** [comment]
Wait, i have this in the ip and port bit, panel1.justbillyh.xyz:2003 ~ that's the url to the panel and the Port

**Comment by TH4RDY** [comment]
Okay, so i added the ip:port and now it's still returning with nil

**Comment by jdwoj5** [comment]
Are you sure the bot is running there? I went to that website and it didn't work.

**Comment by TH4RDY** [comment]
Yh it is running here's the website https://panel.justbillyh.xyz

**Comment by jdwoj5** [comment]
Then your IP is panel.justbillyh.xyz not panel1.justbillyh.xyz

**Comment by TH4RDY** [comment]
Hey, sorry for wasting your time i had to update the docker image on the server. This may be closed.
