### ISSUE TITLE
Whatever I do, it will not start the bot.

### ISSUE THREAD

**Issue by valdemarcrafter** [jdwoj5/hub-linkbot#5]
Whatever I do, it will not start the bot. The console says no error, so I can't find out. The only error I have are `{"status":"error","error":"Service unavailable."}
`

**Comment by valdemarcrafter** [comment]
I found this `PROCESS | Product-Files Folder found!
WEB | Online!
PROCESS | Database found!
(node:879) UnhandledPromiseRejectionWarning: Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/rbd/pnpm-volume/b645137b-80c4-4277-842b-bbbd8a10b628/node_modules/.registry.npmjs.org/discord.js/12.5.1/node_modules/discord.js/src/client/websocket/WebSocketManager.js:258:15)

(node:879) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:879) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by jdwoj5** [comment]
![Image](https://user-images.githubusercontent.com/53838167/106360971-69fca880-62e9-11eb-8cc5-a22be802e6c7.png)

Please refer to the above line of the README on how to fix that issue. (Please read everything in the README next time!)
